[Main]
fBarehandedDamageMult = 1.0
fThrowingDamageMult = 1.0
fThrowRotationSpeed = 2160.0
fThrowRotationSpeedM = 720.0

fThrowSpeed = 2700.0
;arrows moves at 3500-3800 cm/s
;sprinting speed is ~500 cm/s
;running speed is ~300 cm/s

iChargeHitCount = 1
fChargeMagnitude = 1.8

fArrivalTime = 0.69
fCatchingTreshold = 18.0
fArrivalAngleSnap = 0.0
fMjolnirArrivingDelay = 0.2
fArrivalRotationSpeed = 1260.0
fArrivalRotationSpeedM = 720.0
;fArrivalRotationX = 90
;fArrivalRotationY = 0
;fArrivalRotationZ = 180
fArrivalRoadCurveMagnitude = 18.0
bRetroMoveset = 0
bDontHitWhileArriving = 0
bReturnHProjectileAfterLoops = 1

fMaxArrivalSpeed = 7669.0
fMinArrivalSpeed = 1269.0
;I recommend between 869-1969

fMaxAxeStuckAngle = 350.0
fMinAxeStuckAngle = 80.0

fDraupnirExplosionsInterval = 0.24
iDraupnirExplodableCount = 6
;max count is 9

[Rage]
uRageType = 0
bRageBarOpen = 1
uRageBarRot = 0
uRageBarPosX = 137
uRageBarPosY = 645
uRageBarScaleX = 50
uRageBarScaleY = 50
uRageBarTransparency = 69

[Trails]
bDrawTrails = 1
bUsePrecisionTrails = 1
fTrailColorMult = 1.0
fTrailLifetimeMult = 0.5
uTrailColorIndexLeviathan = 6
uTrailColorIndexMjolnir = 2
uTrailColorIndexDraupnir = 5

[Keybindings]
iAxeCallKey = -1
iAimKey = -1
iRunicKey = -1
iFinisherKey = -1
iMediumDistanceKey = -1
iLongDistanceKey = -1
iPowerAttackKey = -1

[Misc]
bDebugModeOpen = 1